### ISSUE TITLE
Unknow message when add playlist

### ISSUE THREAD

**Issue by itskiru** [WeebDev/Commando#77]
Hello,

I'm sorry about writing here today, but when I add a playlist, that spam the console (with 1 error = 1 music into the play). Thats the full message :
` Promise {
  _bitField: 18087936,
  _fulfillmentHandler0:
   { DiscordAPIError: Unknown Message
       at item.request.gen.end (/home/xxx/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:68:65)
       at then (/home/xxx/node_modules/snekfetch/src/index.js:241:21)
       at tryCatcher (/home/xxx/node_modules/bluebird/js/release/util.js:16:23)
       at Promise._settlePromiseFromHandler (/home/xxx/node_modules/bluebird/js/release/promise.js:512:31)
       at Promise._settlePromise (/home/xxx/node_modules/bluebird/js/release/promise.js:569:18)
       at Promise._settlePromise0 (/home/xxx/node_modules/bluebird/js/release/promise.js:614:10)
       at Promise._settlePromises (/home/xxx/node_modules/bluebird/js/release/promise.js:689:18)
       at Async._drainQueue (/home/xxx/node_modules/bluebird/js/release/async.js:133:16)
       at Async._drainQueues (/home/xxx/node_modules/bluebird/js/release/async.js:143:10)
       at Immediate.Async.drainQueues (/home/xxx/node_modules/bluebird/js/release/async.js:17:14)
       at runCallback (timers.js:800:20)
       at tryOnImmediate (timers.js:762:5)
       at processImmediate [as _immediateCallback] (timers.js:733:5)
     name: 'DiscordAPIError',
     message: 'Unknown Message',
     code: 10008 },
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
`

Thanks !

**Comment by itskiru** [comment]
Oh and another bug :

That skip 2 music when you ran the skip command.

**Comment by itskiru** [comment]
suck my dick
